Mint sign up page
Nkuria/Mint-sign-up-page-clone pull request #1
Opened 2020-08-14 09:33 UTC by NtwaliHeritier

This is a clone of the mint sign up page found on www.mint.com.
We completed it using: 
     - HTML
     - CSS
     - Font Awesome Icons
We used flex box in our navigation bar to make it look good.

2020-08-14 19:26 UTC, MuriloRoque requested changes
# Status: Changes requested :red_circle: 

## Hello @NtwaliHeritier and @Nkuria :wave: 

## You have done an amazing job, your page looks awesome, I'm impressed :clap: :clap: :clap: 

## We only need to fix two MINOR issues:

- [ ] Please check my comments in your HTML file below, these are requirements ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png))

- [ ] Please, add a live link to your README file, try using [Raw Githack](https://raw.githack.com/)

## Apart from that, everything is great! :grin: 

## Kindly make the requested changes and submit for another review, please :pray: 

## I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-14 19:26 UTC, MuriloRoque commented on index.html
> +                <input id="email" type="text">
This input should have the type 'email', not 'text'.

2020-08-14 19:26 UTC, MuriloRoque commented on index.html
> +            <button class="nav-btn create">
This button should have the type 'submit'.

2020-08-15 02:22 UTC, lmaldonadoch requested changes
# Changes Required 🥇 🏃‍♂️

## Great job, team!!! 🏆

Your clone is almost identical to the original website; it is quite impressive! :clap: :clap:

There is a small detail that we need to take care of before being able to move on to the next project. Here it goes:

- [ ] [REQUIRED] The product row is not meant to be an image; it should be three pairs of images with the corresponding text.
![image](https://user-images.githubusercontent.com/59229758/90303518-2b2a8180-de74-11ea-921e-337bd48fcec6.png)


- [ ] [OPTIONAL] There is a slightly different color at the top of the page. See if you can implement it!
![image](https://user-images.githubusercontent.com/59229758/90303494-0504e180-de74-11ea-93ae-c4a3778aea85.png)

- [ ] [OPTIONAL] The texts below the phone field, privacy and terms, and reCAPTCHA are larger than on the original website. Try to make it more alike!
![image](https://user-images.githubusercontent.com/59229758/90303505-177f1b00-de74-11ea-9845-4c4aaf603ea1.png)

<img src="https://media.giphy.com/media/SXs1XBbAy9aiHeB5LS/giphy.gif" />

You guys did an amazing job, keep it going! :clap:

Please implement the required changes, and think about the optional ones.

It was a pleasure reviewing your code,

Happy coding! 💻

Slack: Luis Angel Maldoando
[LinkedIn](https://www.linkedin.com/in/lmaldonadoch/)

2020-08-15 20:06 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

## Hello @NtwaliHeritier and @Nkuria :wave: 

## Thank you for making all of the requested changes, your project is approved! You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-15 20:19 UTC, merged